create database VENTAS;

use VENTAS;

CREATE TABLE EMPLEADO(
COD_EMP INT IDENTITY(1,1) PRIMARY KEY,
NOMBRES_EMP VARCHAR(50) NOT NULL,
APE_PATER_EMP VARCHAR(30) NOT NULL,
APE_MATER_EMP VARCHAR(30) NOT NULL,
FECHA_NAC_EMP DATE NOT NULL,
DIRECCION_EMP VARCHAR(50) NOT NULL,
TELEFONO_EMP INT NOT NULL,
CODDIST_EMP VARCHAR(50) NOT NULL,
CORREO_E_EMP VARCHAR(50) NOT NULL,
FECHA_INGRESO_EMP VARCHAR(50) NOT NULL,
COD_SUPERVISOR INT NOT NULL
);

CREATE TABLE DISTRITO(
COD_DIST INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPT_DIST VARCHAR(100) NOT NULL
);

CREATE TABLE BOLETA(
COD_BOL INT IDENTITY(1,1) PRIMARY KEY,
COD_EMP VARCHAR(50) NOT NULL,
FECHA_BOL DATE NOT NULL,
COD__CLI INT NOT NULL,
ESTADO_BOL DATE NOT NULL
);

CREATE TABLE DETALLEBOLETA(
COD_BOL INT IDENTITY(1,1) PRIMARY KEY,
COD_PRO VARCHAR(50) NOT NULL,
CANTIDAD VARCHAR(30) NOT NULL,
PRECIOVENTA VARCHAR(30) NOT NULL,
FOREIGN KEY (COD_BOL) REFERENCES BOLETA (COD_BOL)
);

CREATE TABLE TIPO_PRODUCTO (
    COD_TIPO_PRO INT NOT NULL PRIMARY KEY,
    DESCRIP_TIPO_PRO VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCTO (
    COD_PRO INT NOT NULL PRIMARY KEY,
    DESCRIP_PRO VARCHAR(100) NOT NULL,
    PRECIO_PRO DECIMAL(10, 2) NOT NULL,
    STOCK_ACT_PRO INT NOT NULL,
    STOCK_MIN_PRO INT NOT NULL,
    COD_TIPO_PRO INT NOT NULL,
    FOREIGN KEY (COD_TIPO_PRO) REFERENCES TIPO_PRODUCTO(COD_TIPO_PRO)
);

CREATE TABLE CLIENTE (
    COD_CLI INT NOT NULL PRIMARY KEY,
    DIRECCION_CLI VARCHAR(150) NOT NULL,
    TELEFONO_CLI VARCHAR(20) NOT NULL,
    COD_DIST INT NOT NULL,
    CORREO_E_CLI VARCHAR(100) NULL,
    WEB VARCHAR(100) NULL,
    FOREIGN KEY (COD_DIST) REFERENCES DISTRITO(COD_DIST)
);

CREATE TABLE CLIENTE_PER_JURIDICA (
    COD_CLI INT NOT NULL PRIMARY KEY,
    RAZON_SOCIAL_CLI VARCHAR(150) NOT NULL,
    RUC_CLI CHAR(11) NOT NULL,
    CONTACTO_CLI VARCHAR(100) NULL,
    CARGO_CLI VARCHAR(50) NULL,
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI)
);

CREATE TABLE CLIENTE_PER_NATURAL (
    COD_CLI INT NOT NULL PRIMARY KEY,
    NOMBRES_CLI VARCHAR(100) NOT NULL,
    APE_PATER_CLI VARCHAR(50) NOT NULL,
    APE_MATER_CLI VARCHAR(50) NULL,
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI)
);

ALTER TABLE CLIENTE
ADD DEFAULT 'NO REGISTRA'
FOR CORREO_E_CLI

ALTER TABLE PRODUCTO
ADD CONSTRAINT CHK_PRECIO_PRO
CHECK(PRECIO_PRO >= 0 AND PRECIO_PRO <= 1000);

ALTER TABLE PRODUCTO
ADD DEFAULT 'TIPO01'
FOR COD_TIPO_PRO;



CREATE TABLE CLIENTE_BAK (
    COD_CLI INT NOT NULL PRIMARY KEY IDENTITY,
    DIRECCION_CLI VARCHAR(150) NOT NULL,
    TELEFONO_CLI VARCHAR(20) NOT NULL,
    COD_DIST INT NOT NULL,
    CORREO_E_CLI VARCHAR(100) NULL,
    WEB VARCHAR(100) NULL,
    FOREIGN KEY (COD_DIST) REFERENCES DISTRITO(COD_DIST)
	);

INSERT INTO CLIENTE_BAK (DIRECCION_CLI, TELEFONO_CLI, COD_DIST, CORREO_E_CLI, WEB)
VALUES
('CLL 30 #60-60', '3001478963', 1, 'OMAIRA_ENTERRADA@YAHOO.COM', NULL),
('CLL 30 #60-70', '300148963', 1, 'CAMILORRADA@YAHOO.COM', NULL),
('CLL 30 #60-60', '3001478963', 1, 'TENIENTERRADA@YAHOO.COM', NULL);

INSERT INTO DISTRITO (DESCRIPT_DIST)
VALUES ('L01'), ('LIMA 01'), ('CALLAO');

INSERT INTO TIPO_PRODUCTO (COD_TIPO_PRO, DESCRIP_TIPO_PRO)
VALUES (1, 'Electrónica'), (2, 'Alimentos'), (3, 'Ropa');

INSERT INTO PRODUCTO (COD_PRO, DESCRIP_PRO, PRECIO_PRO, STOCK_ACT_PRO, STOCK_MIN_PRO, COD_TIPO_PRO)
VALUES 
(101, 'Televisor LED', 900.00, 20, 5, 1),
(102, 'Pan integral', 5.50, 100, 20, 2),
(103, 'Polo deportivo', 25.00, 50, 10, 3);

INSERT INTO CLIENTE (COD_CLI, DIRECCION_CLI, TELEFONO_CLI, COD_DIST, CORREO_E_CLI, WEB)
VALUES 
(201, 'Av. Bolívar 123', '999888777', 1, NULL, 'www.cliente1.com'),
(202, 'Jr. Lima 456', '988776655', 2, 'cliente2@correo.com', NULL),
(203, 'Calle Falsa 123', '977665544', 3, NULL, NULL);

INSERT INTO CLIENTE_PER_JURIDICA (COD_CLI, RAZON_SOCIAL_CLI, RUC_CLI, CONTACTO_CLI, CARGO_CLI)
VALUES 
(201, 'Empresa Uno SAC', '20456789012', 'Pedro Gómez', 'Gerente'),
(202, 'Tech Corp S.A.', '20567890123', 'Luisa Ramos', 'Jefa de compras'),
(203, 'Mundo Hogar SRL', '20678901234', 'Carlos Díaz', 'Administrador');


INSERT INTO CLIENTE (COD_CLI, DIRECCION_CLI, TELEFONO_CLI, COD_DIST, CORREO_E_CLI, WEB)
VALUES 
(204, 'Av. Las Palmas 789', '944332211', 1, NULL, NULL),
(205, 'Jr. Progreso 321', '933221100', 2, 'maria@gmail.com', NULL),
(206, 'Calle Sol 101', '922110099', 3, NULL, NULL);

INSERT INTO CLIENTE_PER_NATURAL (COD_CLI, NOMBRES_CLI, APE_PATER_CLI, APE_MATER_CLI)
VALUES 
(204, 'Juan Carlos', 'Rojas', 'Salas'),
(205, 'María Elena', 'Torres', 'Castro'),
(206, 'Luis Alberto', 'Díaz', 'Morales');

INSERT INTO EMPLEADO (NOMBRES_EMP, APE_PATER_EMP, APE_MATER_EMP, FECHA_NAC_EMP, DIRECCION_EMP, TELEFONO_EMP, CODDIST_EMP, CORREO_E_EMP, FECHA_INGRESO_EMP, COD_SUPERVISOR)
VALUES
('Ana', 'Lopez', 'Vargas', '1985-04-23', 'Av. Perú 123', 987654321, '1', 'ana.lopez@mail.com', '2011-03-10', 1),
('Carlos', 'Mejía', 'Torres', '1990-11-05', 'Jr. Arequipa 456', 987123456, '2', 'carlos.mejia@mail.com', '2013-07-15', 1),
('Lucía', 'Soto', 'Fernández', '1992-08-19', 'Calle Lima 789', 986987654, '3', 'lucia.soto@mail.com', '2022-09-20', 2);

INSERT INTO BOLETA (COD_EMP, FECHA_BOL, COD__CLI, ESTADO_BOL)
VALUES
('1', '2024-01-10', 201, '2024-01-10'),
('2', '2024-02-12', 202, '2024-02-12'),
('3', '2024-03-05', 203, '2024-03-05');

INSERT INTO DETALLEBOLETA (COD_PRO, CANTIDAD, PRECIOVENTA)
VALUES
(101, '2', '1800.00'),
(102, '5', '27.50'),
(103, '3', '75.00');

INSERT INTO CLIENTE_BAK (DIRECCION_CLI, TELEFONO_CLI, COD_DIST, CORREO_E_CLI, WEB)
VALUES
('Calle 1', '900000001', 1, 'cliente1@bak.com', NULL),
('Calle 2', '900000002', 2, NULL, 'www.bak2.com'),
('Calle 3', '900000003', 3, NULL, NULL);
